'use strict';

// Maps prop_level values to Markdown heading depths.
var LEVEL_HEADING = {
  'Organization':              2,
  'Software System':           3,
  'Pipeline / Workflow / Tier': 4,
  'Service':                   5,
  'Node':                      6,
};

// Order used when sorting uncategorised shapes.
var LEVEL_ORDER = {
  'Organization':              0,
  'Software System':           1,
  'Pipeline / Workflow / Tier': 2,
  'Service':                   3,
  'Node':                      4,
};

function ArchitectureReport(ui, shapeProps) {
  this.ui = ui;
  this.shapeProps = shapeProps;
}

ArchitectureReport.prototype.generate = function() {
  var ui = this.ui;
  var sp = this.shapeProps;

  // Validate that the file has been saved to disk.
  var file = ui.getCurrentFile();
  if (!file || !file.fileObject || !file.fileObject.path) {
    mxUtils.alert('Save the diagram before generating a report.');
    return;
  }

  var filePath = file.fileObject.path;
  var sep      = filePath.indexOf('/') !== -1 ? '/' : '\\';
  var fileDir  = filePath.substring(0, filePath.lastIndexOf(sep));
  var diagName = _sanitize((file.fileObject.name || 'diagram').replace(/\.[^.]+$/, ''));

  var page     = ui.currentPage;
  var pageName = page
    ? (page.getName ? page.getName() : (page.name || 'page'))
    : 'page';

  var base        = diagName + '_' + _sanitize(pageName);
  var pngFilename = base + '.png';
  var mdFilename  = base + '.md';
  var pngPath     = fileDir + sep + pngFilename;
  var mdPath      = fileDir + sep + mdFilename;

  // Collect eligible shapes on the current page.
  var graph         = ui.editor.graph;
  var eligibleCells = _collectEligible(graph, sp);

  if (eligibleCells.length === 0) {
    mxUtils.alert('No shapes with Name and Level found on this page.');
    return;
  }

  // Export the PNG first, then write the Markdown.
  _exportPng(ui, pngPath, function(pngErr) {
    if (pngErr) {
      mxUtils.alert('PNG export failed: ' + pngErr);
      return;
    }

    var md = _buildMarkdown(sp, graph, eligibleCells, pageName, pngFilename);

    window.electron.request(
      { action: 'writeFile', path: mdPath, data: md, enc: 'utf8' },
      function() {
        mxUtils.alert('Report saved:\n• ' + mdFilename + '\n• ' + pngFilename);
      },
      function(err) {
        mxUtils.alert('Could not write report: ' + (err || 'unknown error'));
      }
    );
  });
};

// ---------------------------------------------------------------------------
// Eligibility
// ---------------------------------------------------------------------------

function _collectEligible(graph, sp) {
  var result = [];
  Object.keys(graph.model.cells).forEach(function(id) {
    var cell = graph.model.cells[id];
    if (!cell.vertex)                          return;
    if (sp.isIgnored(cell))                    return;
    if (!sp.getProperty(cell, sp.PROP_NAME))   return;
    if (!sp.getProperty(cell, sp.PROP_LEVEL))  return;
    result.push(cell);
  });
  return result;
}

// ---------------------------------------------------------------------------
// PNG export via Electron IPC
// ---------------------------------------------------------------------------

function _exportPng(ui, path, callback) {
  try {
    ui.editor.exportToCanvas(
      function(canvas) {
        try {
          var dataUrl = canvas.toDataURL('image/png');
          var base64  = dataUrl.substring(dataUrl.indexOf(',') + 1);
          window.electron.request(
            { action: 'writeFile', path: path, data: base64, enc: 'base64' },
            function()    { callback(null); },
            function(err) { callback(String(err || 'write failed')); }
          );
        } catch (e) {
          callback(String(e));
        }
      },
      null,   // format  — PNG by default
      null,   // imageCache
      null,   // background — use page setting
      function(err) { callback(String(err)); }   // exportToCanvas error callback
    );
  } catch (e) {
    callback(String(e));
  }
}

// ---------------------------------------------------------------------------
// Markdown builder
// ---------------------------------------------------------------------------

function _buildMarkdown(sp, graph, eligibleCells, pageName, pngFilename) {
  var eligibleIds = {};
  eligibleCells.forEach(function(c) { eligibleIds[c.id] = true; });
  var emitted = {};
  var lines   = [];

  // The HTML comment makes the file start with '<!' so DrawIO's writeFile
  // content-type check accepts it. Markdown renderers ignore HTML comments.
  lines.push('<!-- generated by Architect toolset for DrawIO -->');
  lines.push('');
  lines.push('# ' + pageName);
  lines.push('');
  lines.push('![](' + pngFilename + ')');
  lines.push('');

  // Emit all Organisation shapes and their subtrees.
  eligibleCells.forEach(function(cell) {
    if (!emitted[cell.id] && sp.getProperty(cell, sp.PROP_LEVEL) === 'Organization') {
      _emitSubtree(cell, 2, lines, graph, sp, eligibleIds, emitted);
    }
  });

  // Anything not yet emitted goes into the Uncategorised section.
  var uncategorised = eligibleCells.filter(function(c) { return !emitted[c.id]; });

  if (uncategorised.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Uncategorised');
    lines.push('');
    lines.push('*Shapes with properties that are not contained within any Organisation.*');
    lines.push('');

    uncategorised.sort(function(a, b) {
      var la = sp.getProperty(a, sp.PROP_LEVEL) || '';
      var lb = sp.getProperty(b, sp.PROP_LEVEL) || '';
      return (LEVEL_ORDER[la] !== undefined ? LEVEL_ORDER[la] : 99) -
             (LEVEL_ORDER[lb] !== undefined ? LEVEL_ORDER[lb] : 99);
    });

    uncategorised.forEach(function(cell) {
      if (!emitted[cell.id]) {
        var depth = LEVEL_HEADING[sp.getProperty(cell, sp.PROP_LEVEL)] || 3;
        _emitSubtree(cell, depth, lines, graph, sp, eligibleIds, emitted);
      }
    });
  }

  return lines.join('\n');
}

// Recursively emits a cell and all its eligible children.
function _emitSubtree(cell, headingDepth, lines, graph, sp, eligibleIds, emitted) {
  if (emitted[cell.id]) return;
  emitted[cell.id] = true;

  var name  = sp.getProperty(cell, sp.PROP_NAME)        || '(unnamed)';
  var level = sp.getProperty(cell, sp.PROP_LEVEL)       || '';
  var desc  = sp.getProperty(cell, sp.PROP_DESCRIPTION) || '';
  var depth = Math.min(headingDepth, 6);

  lines.push(new Array(depth + 1).join('#') + ' ' + name);
  lines.push('');

  if (level) {
    lines.push('*' + level + '*');
    lines.push('');
  }

  if (desc) {
    // Description is rendered verbatim as Markdown
    lines.push(desc);
    lines.push('');
  }

  var connText = _buildConnectionsText(cell, graph, sp);
  if (connText) {
    lines.push('**Connections:** ' + connText);
    lines.push('');
  }

  // Recurse into eligible model children.
  var children = graph.model.getChildCells(cell, true, false);
  children.forEach(function(child) {
    if (eligibleIds[child.id] && !emitted[child.id]) {
      _emitSubtree(child, depth + 1, lines, graph, sp, eligibleIds, emitted);
    }
  });
}

// Builds the connections inline text for a cell entry.
function _buildConnectionsText(cell, graph, sp) {
  var edges = graph.getEdges(cell);
  if (!edges || edges.length === 0) return '';

  var parts = [];
  edges.forEach(function(edge) {
    var isOutgoing = edge.source === cell;
    var other      = isOutgoing ? edge.target : edge.source;
    if (!other || !other.vertex) return;

    var arrow = isOutgoing ? '→' : '←';

    var rawName  = sp.getProperty(other, sp.PROP_NAME) || graph.getLabel(other) || '';
    var connName = rawName.replace(/<br\s*\/?>/gi, ' ').replace(/<[^>]*>/g, '').trim() || '(unnamed)';

    var rawLabel  = graph.getLabel(edge) || '';
    var edgeLabel = rawLabel.replace(/<br\s*\/?>/gi, ' ').replace(/<[^>]*>/g, '').trim();

    parts.push(arrow + ' ' + connName + (edgeLabel ? ' (' + edgeLabel + ')' : ''));
  });

  return parts.join(', ');
}

// ---------------------------------------------------------------------------
// Filename sanitisation
// ---------------------------------------------------------------------------

function _sanitize(str) {
  return String(str || '')
    .toLowerCase()
    .replace(/\s+/g, '')
    .replace(/[^a-z0-9\-]/g, '')
    .substring(0, 64) || 'unnamed';
}

module.exports = ArchitectureReport;
